# Generated by Django 5.1.5 on 2025-01-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code_used',
            field=models.BooleanField(default=False),
        ),
    ]
